- name: Deploy Story Network Infrastructure
  hosts: story_nodes
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Ubuntu"

  roles:
    - role: common
      tags: ['common']

- name: Deploy Story Execution Nodes
  hosts: execution_nodes
  become: true
  gather_facts: true

  roles:
    - role: story-geth
      tags: ['geth', 'execution']

- name: Deploy Story Consensus Nodes
  hosts: consensus_nodes
  become: true
  gather_facts: true

  roles:
    - role: story-consensus
      tags: ['consensus']