- name: Create necessary directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - "/home/{{ ansible_user }}/go/bin"
    - "{{ home_dir }}/geth"
  become: yes

- name: Download Geth binary
  get_url:
    url: "https://github.com/piplabs/story-geth/releases/download/{{ geth_version }}/geth-linux-amd64"
    dest: "/home/{{ ansible_user }}/go/bin/geth"
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes

- name: Create Geth service file
  template:
    src: story-geth.service.j2
    dest: /etc/systemd/system/story-geth.service
    mode: '0644'
  become: yes