- name: Download Story-geth binary
  get_url:
    url: "{{ geth_binary_url }}"
    dest: "{{ geth_binary_path }}"
    mode: '0755'
    owner: "root"
    group: "root"

- name: Create geth data directory
  file:
    path: "{{ geth_data_dir }}"
    state: directory
    owner: "{{ story_user }}"
    group: "{{ story_user }}"
    mode: '0755'

- name: Generate JWT secret
  shell: |
    openssl rand -hex 32 > {{ jwt_secret_path }}
  args:
    creates: "{{ jwt_secret_path }}"

- name: Set JWT secret permissions
  file:
    path: "{{ jwt_secret_path }}"
    owner: "{{ story_user }}"
    group: "{{ story_user }}"
    mode: '0644'

- name: Create story-geth service
  template:
    src: story-geth.service.j2
    dest: /etc/systemd/system/story-geth.service
    mode: '0644'

- name: Start and enable story-geth service
  systemd:
    name: story-geth
    state: started
    enabled: yes
    daemon_reload: yes